name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test with Go ${{ matrix.go }}
    strategy:
      matrix:
        go: ["1.18", "1.19", "1.20"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - run: go test ./...

  # Vulnmap jobs
  #
  # Rotate the VULNMAP_TOKEN in
  # https://app.vulnmap.khulnasoft.com/org/cloud-cloud/manage/service-accounts if needed, and
  # replace it in the GitHub repository secrets. The service account is named
  # cli-extension-iac-rules-ci.
  vulnmap-oss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Vulnmap to check for vulnerabilities
        uses: khulnasoft-lab/vulnmap-actions/golang@master
        env:
          VULNMAP_TOKEN: ${{ secrets.VULNMAP_TOKEN }}
        with:
          args: --severity-threshold=medium --org=cloud-cloud

  vulnmap-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Vulnmap to check for vulnerabilities
        uses: khulnasoft-lab/vulnmap-actions/golang@master
        env:
          VULNMAP_TOKEN: ${{ secrets.VULNMAP_TOKEN }}
        with:
          command: code
          args: test --severity-threshold=medium --org=cloud-cloud
